# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
  OrdererOrgs:
    # ---------------------------------------------------------------------------
    # Orderer
    # ---------------------------------------------------------------------------
    - Name: Orderer
      Domain: triterras.com
      EnableNodeOUs: true

      Specs:
        - Hostname: orderer
        - Hostname: orderer2
        - Hostname: orderer3
        - Hostname: orderer4
        - Hostname: orderer5
  
  # ---------------------------------------------------------------------------
  # "PeerOrgs" - Definition of organizations managing peer nodes
  # ---------------------------------------------------------------------------
  PeerOrgs:
    # ---------------------------------------------------------------------------
    # Org1
    # ---------------------------------------------------------------------------
    - Name: Seller
      Domain: seller.triterras.com
      EnableNodeOUs: true
      Template:
        Count: 2
      Users:
        Count: 1

    # ---------------------------------------------------------------------------
    # Org2:
    # ---------------------------------------------------------------------------
    - Name: Trader
      Domain: trader.triterras.com
      EnableNodeOUs: true
      Template:
        Count: 2
      Users:
        Count: 1
  
    # ---------------------------------------------------------------------------
    # Org3:
    # ---------------------------------------------------------------------------
    - Name: Buyer
      Domain: buyer.triterras.com
      EnableNodeOUs: true
      Template:
        Count: 2
      Users:
        Count: 1

    # ---------------------------------------------------------------------------
    # Org4:
    # ---------------------------------------------------------------------------
    - Name: Banker
      Domain: banker.triterras.com
      EnableNodeOUs: true
      Template:
        Count: 2
      Users:
        Count: 1

    # ---------------------------------------------------------------------------
    # Org5:
    # ---------------------------------------------------------------------------
    - Name: Shipper
      Domain: shipper.triterras.com
      EnableNodeOUs: true
      Template:
        Count: 2
      Users:
        Count: 1
  